# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8da1b28516e934faa96177f7431b8bd1ccbb153c7de5a18ba7a2eb6464b744760a2e4af54b0d4b87a4589e558c6aa5d1889790dede390291128847b40fd4a88

test:
  secret_key_base: 91dbebd370da822f42d96b2527ab58671a2f7cad6e77b694dd0780ddae149be1718823573a876d7fc669fe9fba06a740ede71ff0cd3c54d3d99bb77942aad72b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
